/**
 * Automated Institutional Resume Generator.
 *
 * Renders a standardized single-page college placement resume from the
 * student's profile (academics, skills, projects, portfolios) into the
 * institutional template — clean serif typography, TPO verification seal,
 * and a print pipeline for PDF export.
 */

import type { StudentProfile } from "@/types";

export interface ResumeProject {
  title: string;
  techStack: string[];
  description: string;
  githubUrl?: string;
}

export interface ResumeData {
  student: StudentProfile;
  batch: string;
  projects: ResumeProject[];
  leetcodeUrl?: string;
}

const escape = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

/**
 * Render the institutional resume HTML — single-page constraint enforced
 * through compact spacing rules; the print stylesheet keeps it to one page.
 */
export function renderResumeHtml(data: ResumeData): string {
  const { student, batch, projects, leetcodeUrl } = data;
  const name = escape(student.name);
  const contactBits = [
    escape(student.email),
    student.phone ? escape(student.phone) : null,
    student.githubUrl ? "github.com/" + escape(student.githubUrl.replace(/^https?:\/\/(www\.)?github\.com\//, "")) : null,
    student.linkedinUrl ? "linkedin.com/in/" + escape(student.linkedinUrl.replace(/^https?:\/\/(www\.)?linkedin\.com\/in\//, "")) : null,
    leetcodeUrl ? "leetcode/" + escape(leetcodeUrl.replace(/^https?:\/\/(www\.)?leetcode\.com\//, "")) : null,
  ].filter(Boolean) as string[];

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>${name} — Placement Resume</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Georgia', 'Times New Roman', serif; color: #1a1a2e; background: #fff; padding: 36px 44px; max-width: 800px; margin: 0 auto; font-size: 12px; line-height: 1.45; }
  h1 { font-size: 22px; text-align: center; letter-spacing: 1.5px; text-transform: uppercase; color: #4c1d95; }
  .contact { text-align: center; font-size: 10.5px; color: #4b5563; margin-top: 4px; }
  .contact span { margin: 0 7px; }
  .vbadge { text-align: center; font-size: 9px; color: #b45309; margin-top: 5px; letter-spacing: 0.8px; text-transform: uppercase; font-family: Arial, sans-serif; }
  h2 { font-size: 11.5px; text-transform: uppercase; letter-spacing: 1.6px; color: #4c1d95; border-bottom: 1.5px solid #7c3aed; padding-bottom: 3px; margin: 16px 0 8px; }
  .edu-table { width: 100%; border-collapse: collapse; }
  .edu-table td { padding: 2.5px 0; font-size: 12px; }
  .edu-table .right { text-align: right; color: #4b5563; }
  .skills { font-size: 11.5px; }
  .skills strong { color: #4c1d95; }
  .project { margin-bottom: 9px; }
  .project-head { display: flex; justify-content: space-between; align-items: baseline; }
  .project-title { font-weight: 700; font-size: 12.5px; }
  .project-tech { font-size: 9.5px; color: #b45309; font-family: Arial, sans-serif; }
  .project-desc { font-size: 11.5px; color: #374151; margin-top: 1.5px; }
  .project-link { font-size: 9.5px; color: #7c3aed; }
  footer { margin-top: 18px; border-top: 1px dashed #7c3aed; padding-top: 8px; text-align: center; font-size: 8.5px; color: #6b7280; font-family: Arial, sans-serif; letter-spacing: 0.5px; }
  @page { size: A4; margin: 12mm; }
  @media print { body { padding: 0; } }
</style>
</head>
<body>
  <h1>${name}</h1>
  <div class="contact">${contactBits.map((b) => `<span>${b}</span>`).join("·")}</div>
  ${student.isVerified ? '<div class="vbadge">✦ Academically Verified — Training &amp; Placement Cell</div>' : ""}

  <h2>Education</h2>
  <table class="edu-table">
    <tr>
      <td><strong>${escape("College of Engineering")}</strong> — B.Tech ${escape(student.department)}</td>
      <td class="right">Batch of ${escape(String(student.graduationYear))}${batch ? ` · ${escape(batch)}` : ""}</td>
    </tr>
    <tr>
      <td>CGPA: <strong>${student.cgpa.toFixed(2)} / 10</strong> (Verified)</td>
      <td class="right">Active Backlogs: ${student.activeBacklogs}</td>
    </tr>
  </table>

  ${
    student.skills.length > 0
      ? `<h2>Technical Skills</h2>
  <p class="skills"><strong>${student.skills.map(escape).join("</strong> · <strong>")}</strong></p>`
      : ""
  }

  ${
    projects.length > 0
      ? `<h2>Projects</h2>
  ${projects
    .map(
      (p) => `<div class="project">
    <div class="project-head">
      <span class="project-title">${escape(p.title)}</span>
      <span class="project-tech">${p.techStack.map(escape).join(" · ")}</span>
    </div>
    <p class="project-desc">${escape(p.description)}</p>
    ${p.githubUrl ? `<a class="project-link" href="${escape(p.githubUrl)}">${escape(p.githubUrl)}</a>` : ""}
  </div>`,
    )
    .join("")}`
      : ""
  }

  <footer>Generated by the College Placement Portal • Institutionally formatted • ${new Date().toLocaleDateString("en-IN", { month: "long", year: "numeric" })}</footer>
</body>
</html>`;
}

/** Open the resume in a print window for PDF export. */
export function downloadResumePdf(data: ResumeData): boolean {
  try {
    const win = window.open("", "_blank", "width=900,height=1000");
    if (!win) return false;
    win.document.write(renderResumeHtml(data));
    win.document.close();
    win.focus();
    window.setTimeout(() => {
      try {
        win.print();
      } catch {
        /* user prints manually */
      }
    }, 450);
    return true;
  } catch {
    return false;
  }
}
